#!/bin/bash 

dev=$1

echo "Streaming footage over UDP"

#Open terminal to listen on UDP port
gnome-terminal -- bash -c "ffplay udp://127.0.0.1:1234;exec bash"
echo "New terminal open to listen on UDP port";

#Capture footage and stream over UDP
$PWD/capture.out -d $dev -o -c0|ffmpeg -i - -c:v libx264 -f mpegts udp://127.0.0.1:1234
